# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 614ec61b0aee12bdfc110a1989375e689f727a29e44a9fd1c44e4bbbf05d2b33a7ff31f2e3410718bf9fa34e43fa245a638831703d4e3451793740dcc37a2805

test:
  secret_key_base: 543fae214e55667b4195f48f1f6384f9b029ad0f21902280ddd2ee6f7be9750c29cd4a7ca9015ef63e7fec8c5a442544b8f1fff3d40cd0c1d7c5e910ba4bfb48

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
